---
all:
  children:
    wazuh_manager:
      hosts:
        wazuh-manager:
          ansible_host: 192.168.56.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    
    ubuntu_web:
      hosts:
        ubuntu-web:
          ansible_host: 192.168.56.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    
    rocky_db:
      hosts:
        rocky-db:
          ansible_host: 192.168.56.30
          ansible_user: vagrant
          ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key

  vars:
    wazuh_manager_ip: 192.168.56.10
    environment: dev