---
# Wazuh SOC Lab Inventory
# Update IP addresses to match your VM deployment

all:
  children:
    wazuh_managers:
      hosts:
        wazuh-manager:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wazuh_manager_ip: 192.168.1.10
          wazuh_cluster_node_type: master

    linux_agents:
      hosts:
        ubuntu-web:
          ansible_host: 192.168.2.10
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wazuh_agent_name: ubuntu-web-server
          wazuh_agent_groups: ["web", "dmz"]

        rhel-db:
          ansible_host: 192.168.3.20
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          wazuh_agent_name: rhel-database
          wazuh_agent_groups: ["database", "internal"]

    windows_agents:
      hosts:
        windows-dc:
          ansible_host: 192.168.3.10
          ansible_user: Administrator
          ansible_password: "{{ vault_windows_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          wazuh_agent_name: windows-domain-controller
          wazuh_agent_groups: ["windows", "domain_controller", "internal"]

    network_devices:
      hosts:
        pfsense-fw:
          ansible_host: 192.168.1.1
          device_type: pfsense
          syslog_target: 192.168.1.10
          syslog_port: 514

  vars:
    # Global Wazuh configuration
    wazuh_manager_ip: 192.168.1.10
    wazuh_manager_port: 1514
    wazuh_registration_port: 1515
    wazuh_cluster_port: 1516

    # Network configuration
    management_network: 192.168.1.0/24
    dmz_network: 192.168.2.0/24
    internal_network: 192.168.3.0/24

    # Lab-specific settings
    lab_domain: lab.local
    lab_environment: development

    # Security settings
    wazuh_agent_auth_password: "{{ vault_agent_auth_password }}"
    enable_fim: true
    enable_rootcheck: true
    enable_sca: true
