---
# Global variables for all hosts in the Wazuh SOC Lab

# Wazuh Manager Configuration
wazuh_manager:
  version: "4.7.0"
  api_port: 55000
  cluster_port: 1516
  registration_port: 1515
  agent_port: 1514

# Wazuh Agent Configuration
wazuh_agent:
  version: "4.7.0"
  config_profile: soc-lab
  log_format: plain

# Network Configuration
networks:
  management:
    cidr: "192.168.1.0/24"
    gateway: "192.168.1.1"
  dmz:
    cidr: "192.168.2.0/24"
    gateway: "192.168.1.1"
  internal:
    cidr: "192.168.3.0/24"
    gateway: "192.168.1.1"

# DNS Configuration
dns_servers:
  - "192.168.3.10" # Windows DC
  - "8.8.8.8" # Google DNS fallback

# NTP Configuration
ntp_servers:
  - "pool.ntp.org"
  - "time.google.com"

# Security Configuration
security:
  enable_firewall: true
  enable_selinux: true
  disable_root_login: true
  password_complexity: true

# Monitoring Configuration
monitoring:
  enable_fim: true
  enable_rootcheck: true
  enable_sca: true
  enable_vulnerability_detection: true

# Log Retention
log_retention:
  hot_storage_days: 30
  warm_storage_days: 90
  cold_storage_days: 365

# Backup Configuration
backup:
  enabled: true
  schedule: "0 2 * * *" # Daily at 2 AM
  retention_days: 30

# Lab Environment Settings
lab:
  domain: "lab.local"
  environment: "development"
  timezone: "UTC"

# Package repositories
repositories:
  wazuh_repo: "https://packages.wazuh.com/4.x"
  elastic_repo: "https://artifacts.elastic.co/packages/7.x"
