---
# Linux-specific configuration for Wazuh agents

# Package management
package_manager: apt # Override in host_vars for RHEL systems

# Wazuh Agent Linux Configuration
wazuh_agent_linux:
  config_file: "/var/ossec/etc/ossec.conf"
  log_file: "/var/ossec/logs/ossec.log"
  bin_dir: "/var/ossec/bin"
  queue_dir: "/var/ossec/queue"

# System monitoring
system_monitoring:
  log_files:
    - "/var/log/auth.log"
    - "/var/log/syslog"
    - "/var/log/kern.log"
    - "/var/log/dpkg.log"

  directories_fim:
    - "/etc"
    - "/usr/bin"
    - "/usr/sbin"
    - "/bin"
    - "/sbin"

  ignore_files:
    - "/etc/mtab"
    - "/etc/hosts.deny"
    - "/etc/mail/statistics"
    - "/etc/random-seed"
    - "/etc/adjtime"

# Security hardening
security_hardening:
  disable_unused_services: true
  configure_fail2ban: true
  update_packages: true

# Firewall rules for Wazuh agent
firewall_rules:
  - port: 1514
    protocol: tcp
    direction: outbound
    destination: "{{ wazuh_manager_ip }}"
    comment: "Wazuh agent communication"
  - port: 1515
    protocol: tcp
    direction: outbound
    destination: "{{ wazuh_manager_ip }}"
    comment: "Wazuh agent registration"

# Log rotation
logrotate_config:
  wazuh_logs:
    path: "/var/ossec/logs/*.log"
    frequency: daily
    rotate: 30
    compress: true
    delaycompress: true

# Cron jobs
cron_jobs:
  - name: "Wazuh agent health check"
    job: "/var/ossec/bin/wazuh-control status > /dev/null || systemctl restart wazuh-agent"
    minute: "*/5"

# Performance tuning
performance:
  max_events_per_second: 500
  queue_size: 16384

# Custom rules for Linux systems
custom_rules:
  - rule_id: 100001
    description: "SSH brute force attack detected"
    pattern: "authentication failure.*ssh"
    frequency: 5
    timeframe: 300

  - rule_id: 100002
    description: "Suspicious file modification in /etc"
    pattern: "File.*modified.*in /etc"
    frequency: 1
    timeframe: 60
