# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Global VM settings
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Wazuh Manager + ELK Stack
  config.vm.define "wazuh-manager" do |wazuh|
    wazuh.vm.box = "ubuntu/jammy64"
    wazuh.vm.hostname = "wazuh-manager"
    wazuh.vm.network "private_network", ip: "192.168.56.10"
    
    wazuh.vm.provider "virtualbox" do |vb|
      vb.name = "wazuh-manager"
      vb.memory = "6144"
      vb.cpus = 4
    end
    
    wazuh.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y python3-pip
      pip3 install ansible
    SHELL
  end

  # Ubuntu Web Server (DVWA)
  config.vm.define "ubuntu-web" do |web|
    web.vm.box = "ubuntu/jammy64"
    web.vm.hostname = "ubuntu-web"
    web.vm.network "private_network", ip: "192.168.56.20"
    
    web.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-web"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Rocky Linux Database Server
  config.vm.define "rocky-db" do |db|
    db.vm.box = "generic/rocky9"
    db.vm.hostname = "rocky-db"
    db.vm.network "private_network", ip: "192.168.56.30"
    
    db.vm.provider "virtualbox" do |vb|
      vb.name = "rocky-db"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  # Windows Server (Optional - comment out if not needed)
  # config.vm.define "windows-dc" do |win|
  #   win.vm.box = "gusztavvargadr/windows-server-2019-standard"
  #   win.vm.hostname = "windows-dc"
  #   win.vm.network "private_network", ip: "192.168.56.40"
  #   
  #   win.vm.provider "virtualbox" do |vb|
  #     vb.name = "windows-dc"
  #     vb.memory = "4096"
  #     vb.cpus = 2
  #   end
  # end
end