---
# Main playbook for Wazuh SOC Lab deployment
# This playbook orchestrates the complete lab setup

- name: Deploy Wazuh SOC Lab Environment
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display lab deployment banner
      debug:
        msg: |
          ================================================
          Wazuh SOC Lab Deployment Starting
          ================================================
          Manager: {{ wazuh_manager_ip }}
          Environment: {{ lab.environment }}
          Domain: {{ lab.domain }}
          ================================================

# Deploy Wazuh Manager (if not already installed)
- import_playbook: deploy-wazuh-manager.yml
  when: "'wazuh_managers' in group_names"

# Deploy Linux agents
- import_playbook: deploy-linux-agents.yml
  when: "'linux_agents' in group_names"

# Deploy Windows agents
- import_playbook: deploy-windows-agents.yml
  when: "'windows_agents' in group_names"

# Configure monitoring and detection rules
- import_playbook: configure-monitoring.yml

# Set up dashboards and visualizations
- import_playbook: configure-dashboards.yml

# Configure backup and maintenance
- import_playbook: configure-backup.yml

# Final verification and testing
- name: Lab Deployment Verification
  hosts: all
  gather_facts: true
  tasks:
    - name: Verify Wazuh agent connectivity
      uri:
        url: "https://{{ wazuh_manager_ip }}:{{ wazuh_manager.api_port }}/agents"
        method: GET
        headers:
          Authorization: "Bearer {{ wazuh_api_token | default('') }}"
        validate_certs: false
      delegate_to: localhost
      when: inventory_hostname != wazuh_manager_ip

    - name: Display deployment summary
      debug:
        msg: |
          ================================================
          Wazuh SOC Lab Deployment Complete
          ================================================
          Access Points:
          - Wazuh Dashboard: https://{{ wazuh_manager_ip }}
          - DVWA: http://{{ hostvars['ubuntu-web']['ansible_host'] }}/dvwa
          - pfSense: https://{{ hostvars['pfsense-fw']['ansible_host'] }}

          Next Steps:
          1. Access Wazuh dashboard and verify agent status
          2. Run attack simulations to test detection
          3. Review generated alerts and dashboards
          ================================================
      run_once: true
      delegate_to: localhost
