all:
  hosts:
    wazuh:
      ansible_host: 192.168.56.10
    web:
      ansible_host: 192.168.56.20
    db:
      ansible_host: 192.168.56.30
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key